spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ug_inventory_management
spring.datasource.username=root
spring.datasource.password=password
server.servlet.session.cookie.same-site=Lax
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8082

#Spring security
logging.level.org.springframework.security=DEBUG
security.jwt.secret-key=
security.jwt.expiration-time=3600000

#Bootstrap Credentials
app.bootstrap-admin.username=rootadmin
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD}

inventory.rollover.enabled=true
inventory.rollover.cron=0 0 0 1 * *
inventory.rollover.zone=Asia/Kolkata