#spring.application.name=ug_inventory_management
#spring.datasource.url=jdbc:mysqlserver://localhost:3306;databaseName=umed_group_inventory
#spring.datasource.username=root
#spring.datasource.password=Sharan@1383
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.application.name=ug_inventory_management

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=umed_group_inventory
spring.datasource.username=root
spring.datasource.password=Sharan@1383

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
